=== huli2000/JavaFullStack/xml-demos/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/products"
	xmlns:tns="http://www.example.org/products"
	elementFormDefault="qualified">

	<element name="products">
		<complexType>
			<sequence>
				<element name="product" type="tns:product" minOccurs="0"
					maxOccurs="unbounded">
				</element>
			</sequence>
		</complexType>
	</element>
	<complexType name="product">
		<sequence>
			<element name="id" type="int"></element>
			<element name="name" type="string"></element>
			<element name="price" type="tns:price"></element>
		</sequence>
	</complexType>
	<simpleType name="price">
		<restriction base="double">
			<minInclusive value="0"></minInclusive>
			<maxInclusive value="100"></maxInclusive>
		</restriction>
	</simpleType>
</schema>

=== huli2000/JavaFullStack/xml-demos/products.xml
<?xml version="1.0" encoding="UTF-8"?>


<products xmlns="http://www.example.org/products"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/products products.xsd">
	<product>
		<id>101</id>
		<name>milk</name>
		<price>25</price>
	</product>
	<product>
		<id>102</id>
		<name>bread</name>
		<price>30</price>
	</product>
	<product>
		<id>103</id>
		<name>TV</name>
		<price>99</price>
	</product>

</products>
